package com.sysout.app.serial.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sysout.app.serial.entity.SerialCommand;

import com.sysout.app.serial.db.SerialCommandDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig serialCommandDaoConfig;

    private final SerialCommandDao serialCommandDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        serialCommandDaoConfig = daoConfigMap.get(SerialCommandDao.class).clone();
        serialCommandDaoConfig.initIdentityScope(type);

        serialCommandDao = new SerialCommandDao(serialCommandDaoConfig, this);

        registerDao(SerialCommand.class, serialCommandDao);
    }
    
    public void clear() {
        serialCommandDaoConfig.clearIdentityScope();
    }

    public SerialCommandDao getSerialCommandDao() {
        return serialCommandDao;
    }

}
